{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "652332da",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      " * Serving Flask app 'fast_dash.fast_dash' (lazy loading)\n",
      " * Environment: production\n",
      "\u001b[31m   WARNING: This is a development server. Do not use it in a production deployment.\u001b[0m\n",
      "\u001b[2m   Use a production WSGI server instead.\u001b[0m\n",
      " * Debug mode: off\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      " * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)\n",
      "127.0.0.1 - - [17/Jun/2022 19:44:03] \"GET / HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [17/Jun/2022 19:44:03] \"GET /_dash-layout HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [17/Jun/2022 19:44:03] \"GET /_dash-dependencies HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [17/Jun/2022 19:44:03] \"GET /assets/favicon.ico?m=1655248671.9738972 HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [17/Jun/2022 19:44:03] \"POST /_dash-update-component HTTP/1.1\" 200 -\n",
      "127.0.0.1 - - [17/Jun/2022 19:44:03] \"GET /assets/favicon.ico?m=1655248671.9738972 HTTP/1.1\" 304 -\n",
      "127.0.0.1 - - [17/Jun/2022 19:44:06] \"POST /_dash-update-component HTTP/1.1\" 200 -\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/fast_dash/fast_dash.py\", line 156, in process_input\n",
      "    output_state = self.callback_fn(*args[:-2])\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 47, in image_to_image\n",
      "    prediction = predict(image)\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 30, in predict\n",
      "    os.chdir(directory)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'model_to_load'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/fast_dash/fast_dash.py\", line 156, in process_input\n",
      "    output_state = self.callback_fn(*args[:-2])\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 47, in image_to_image\n",
      "    prediction = predict(image)\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 30, in predict\n",
      "    os.chdir(directory)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'model_to_load'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/fast_dash/fast_dash.py\", line 156, in process_input\n",
      "    output_state = self.callback_fn(*args[:-2])\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 47, in image_to_image\n",
      "    prediction = predict(image)\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 30, in predict\n",
      "    os.chdir(directory)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'model_to_load'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/fast_dash/fast_dash.py\", line 156, in process_input\n",
      "    output_state = self.callback_fn(*args[:-2])\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 47, in image_to_image\n",
      "    prediction = predict(image)\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 30, in predict\n",
      "    os.chdir(directory)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'model_to_load'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/fast_dash/fast_dash.py\", line 156, in process_input\n",
      "    output_state = self.callback_fn(*args[:-2])\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 47, in image_to_image\n",
      "    prediction = predict(image)\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 30, in predict\n",
      "    os.chdir(directory)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'model_to_load'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/fast_dash/fast_dash.py\", line 156, in process_input\n",
      "    output_state = self.callback_fn(*args[:-2])\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 47, in image_to_image\n",
      "    prediction = predict(image)\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 30, in predict\n",
      "    os.chdir(directory)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'model_to_load'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/fast_dash/fast_dash.py\", line 156, in process_input\n",
      "    output_state = self.callback_fn(*args[:-2])\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 47, in image_to_image\n",
      "    prediction = predict(image)\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 30, in predict\n",
      "    os.chdir(directory)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'model_to_load'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/fast_dash/fast_dash.py\", line 156, in process_input\n",
      "    output_state = self.callback_fn(*args[:-2])\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 47, in image_to_image\n",
      "    prediction = predict(image)\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 30, in predict\n",
      "    os.chdir(directory)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'model_to_load'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/fast_dash/fast_dash.py\", line 156, in process_input\n",
      "    output_state = self.callback_fn(*args[:-2])\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 47, in image_to_image\n",
      "    prediction = predict(image)\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 30, in predict\n",
      "    os.chdir(directory)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'model_to_load'\n",
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/fast_dash/fast_dash.py\", line 156, in process_input\n",
      "    output_state = self.callback_fn(*args[:-2])\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 47, in image_to_image\n",
      "    prediction = predict(image)\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 30, in predict\n",
      "    os.chdir(directory)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'model_to_load'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Exception on /_dash-update-component [POST]\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 2073, in wsgi_app\n",
      "    response = self.full_dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1518, in full_dispatch_request\n",
      "    rv = self.handle_user_exception(e)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1516, in full_dispatch_request\n",
      "    rv = self.dispatch_request()\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/flask/app.py\", line 1502, in dispatch_request\n",
      "    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1078, in dispatch\n",
      "    response.set_data(func(*args, outputs_list=outputs_list))\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/dash/dash.py\", line 1009, in add_context\n",
      "    output_value = func(*args, **kwargs)  # %% callback invoked %%\n",
      "  File \"/Users/florentmargery/miniforge3/envs/fastdash_test/lib/python3.9/site-packages/fast_dash/fast_dash.py\", line 156, in process_input\n",
      "    output_state = self.callback_fn(*args[:-2])\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 47, in image_to_image\n",
      "    prediction = predict(image)\n",
      "  File \"/var/folders/j4/7y0hj60n09q_n50qxfl1rr4w0000gn/T/ipykernel_26014/1170667757.py\", line 30, in predict\n",
      "    os.chdir(directory)\n",
      "FileNotFoundError: [Errno 2] No such file or directory: 'model_to_load'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [17/Jun/2022 19:44:08] \"POST /_dash-update-component HTTP/1.1\" 500 -\n",
      "2022-06-17 19:44:23.659129: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "1/1 [==============================] - 3s 3s/step\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "127.0.0.1 - - [17/Jun/2022 19:44:25] \"POST /_dash-update-component HTTP/1.1\" 200 -\n"
     ]
    }
   ],
   "source": [
    "from fast_dash import FastDash\n",
    "from fast_dash.Components import Image, UploadImage, Text\n",
    "from keras.utils import load_img, img_to_array\n",
    "from keras.utils import load_img\n",
    "from keras.applications.inception_resnet_v2 import preprocess_input\n",
    "from tensorflow import keras\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "import os\n",
    "import tensorflow as tf\n",
    "import base64\n",
    "import numpy as np\n",
    "\n",
    "def preprocess_and_decode(img_str, new_shape=[128,128]):\n",
    "    image_type, img_str = img_str.split(',')\n",
    "    img = base64.b64decode(img_str)\n",
    "    img = tf.image.decode_jpeg(img, channels=3)\n",
    "    img = tf.image.resize(img, new_shape, method=tf.image.ResizeMethod.BILINEAR)\n",
    "    img = img/255.\n",
    "    # if you need to squeeze your input range to [0,1] or [-1,1] do it here\n",
    "    return img\n",
    "def transform_image(image):\n",
    "    img = img_to_array(image)  # Convertir en tableau numpy\n",
    "    img = img.reshape((1, img.shape[0], img.shape[1], img.shape[2]))  # Créer la collection d'images (un seul échantillon)\n",
    "    #img = preprocess_input(img)  # Prétraiter l'image comme le veut VGG-16\n",
    "    return img\n",
    "\n",
    "def predict(image) : \n",
    "    os.chdir('..')\n",
    "    directory = \"model_to_load\" \n",
    "    os.chdir(directory)\n",
    "    model = keras.models.load_model('Model_trained_2')\n",
    "    image = model.predict(image)\n",
    "    return image\n",
    "\n",
    "def untransform_image(prediction):\n",
    "    directory = \"Encoder\" \n",
    "    os.chdir(directory)\n",
    "    encoder = LabelEncoder()\n",
    "    encoder.classes_ = np.load('classes.npy')\n",
    "    \n",
    "    dog_class = encoder.inverse_transform([np.argmax(prediction)])\n",
    "    return dog_class\n",
    "\n",
    "def image_to_image(image):\n",
    "    image = preprocess_and_decode(image)\n",
    "    image = transform_image(image)\n",
    "    prediction = predict(image)\n",
    "    dog_class = untransform_image(prediction)\n",
    "    return dog_class\n",
    "\n",
    "# 2. Define components and initialize app\n",
    "app = FastDash(callback_fn=image_to_image, \n",
    "               inputs=UploadImage, \n",
    "               outputs=Text,\n",
    "               title='Dog Classification',\n",
    "               theme='FLATLY')\n",
    "# 3. Deploy!\n",
    "app.run()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1aa11554",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
